/*
 * This source file was generated by the Gradle 'init' task
 */
package lang

sealed interface TokenValue {
    data object None : TokenValue

    // literal
    data class Number(val value: Double) : TokenValue
    data class Ident(val name: String) : TokenValue

    // oprator
    data object Plus : TokenValue
    data object Minus : TokenValue
    data object Star : TokenValue
    data object Slash : TokenValue
}

data class Token(
    val value: TokenValue,
    val line: Int,
    val col: Int,
)

fun tokenizerRun(input: String): List<Token> {
    val tokens = mutableListOf<Token>()

    var line = 1
    var col = 1
    var idx = 0

    while (idx < input.length) {
        var ch = input[idx]

        when (ch) {
            '\n' -> {
                line += 1
                col = 1
                idx += 1
                continue
            }

            '+' -> tokens.add(Token(TokenValue.Plus, line, col))
            '-' -> tokens.add(Token(TokenValue.Minus, line, col))
            '*' -> tokens.add(Token(TokenValue.Star, line, col))
            '/' -> tokens.add(Token(TokenValue.Slash, line, col))
            else -> {
                fun isNumeric(ch: Char): Boolean {
                    return '0' <= ch && ch <= '9'
                }

                fun isAlpha(ch: Char): Boolean {
                    return 'a' <= ch && ch <= 'z' || 'A' <= ch && ch <= 'Z' || ch == '_'
                }

                if (isNumeric(ch)) {
                    val startIdx = idx
                    val startCol = col

                    idx += 1
                    col += 1

                    while (idx < input.length && (isNumeric(input[idx]) || input[idx] == '.')) {
                        idx += 1
                        col += 1
                    }

                    val value = input.substring(startIdx, idx).toDouble()
                    tokens.add(Token(TokenValue.Number(value), line, startCol))
                    continue
                }

                if (isAlpha(ch)) {
                    val startIdx = idx
                    val startCol = col

                    idx += 1
                    col += 1

                    while (idx < input.length && (isAlpha(input[idx]) || isNumeric(input[idx]))) {
                        idx += 1
                        col += 1
                    }

                    val value = input.substring(startIdx, idx)
                    tokens.add(Token(TokenValue.Ident(value), line, startCol))
                    continue
                }
            }
        }

        col++
        idx++
    }

    return tokens
}

sealed interface Expression {
    data class NumberLiteral(val value: Double) : Expression
    data class Unary(val operator: TokenValue, val operand: Expression) : Expression
    data class Binary(val operator: TokenValue, val left: Expression, val right: Expression) : Expression
}

class Parser(
    val tokens: List<Token>,
    var idx: Int = 0,
) {
    fun peek(): Token? {
        return if (idx < tokens.size) tokens[idx] else null
    }

    fun parseNumberLiteral(): Expression {
        // literal => NUMBER

        val token = this.peek()
        check(token != null) { "Unexpected end of input" }
        check(token.value is TokenValue.Number) { "Unexpected token: ${token.value}" }

        this.idx += 1

        return Expression.NumberLiteral(token.value.value)
    }

    fun parseUnary(): Expression {
        // unary => '-' unary | '+' unary | NUMBER

        val token = this.peek()
        if (token != null && (token.value is TokenValue.Minus || token.value is TokenValue.Plus)) {
            this.idx += 1
            return Expression.Unary(
                operator = token.value,
                operand = this.parseUnary(),
            )
        }

        return this.parseNumberLiteral()
    }

    fun parseTerm(): Expression {
        // term => unary (('*' | '/') unary)*

        val left = this.parseUnary()

        val operator = this.peek()
        if (operator != null && (operator.value is TokenValue.Star || operator.value is TokenValue.Slash)) {
            this.idx += 1

            val right = this.parseTerm()
            return Expression.Binary(operator = operator.value, left = left, right = right)
        }

        return left
    }

    public fun parseExpression(): Expression {
        // expression => term (('+' | '-') term)*

        val left = this.parseTerm()

        val operator = this.peek()
        if (operator != null && (operator.value is TokenValue.Plus || operator.value is TokenValue.Minus)) {
            this.idx += 1

            val right = this.parseExpression()
            return Expression.Binary(operator = operator.value, left = left, right = right)
        }

        return left
    }
}


fun main() {
    val parser = Parser(listOf())
    parser.parseExpression()
}
