/*
 * This source file was generated by the Gradle 'init' task
 */
package lang

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class TokenizerTest {
    @Test
    fun `tokenizes input successfully`() {
        val input = "+-* /"
        val tokens = tokenizerRun(input)

        val expected = listOf(
            Token(TokenValue.Plus, 1, 1),
            Token(TokenValue.Minus, 1, 2),
            Token(TokenValue.Star, 1, 3),
            Token(TokenValue.Slash, 1, 5),
        )

        assertTrue(tokens.size == expected.size)
        for (i in tokens.indices) {
            assertEquals(expected[i], tokens[i])
        }
    }

    @Test
    fun `tokenizes number`() {
        val input = "123.45"
        val tokens = tokenizerRun(input)

        val expected = listOf(
            Token(TokenValue.Number(123.45), 1, 1)
        )

        assertTrue(tokens.size == expected.size)
        for (i in tokens.indices) {
            assertEquals(expected[i], tokens[i])
        }
    }
}

class ParserTest {
    @Test
    fun `parses number`() {
        val tokens = listOf(Token(TokenValue.Number(123.45), 1, 1))
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        assertTrue(expr is Expression.NumberLiteral)
        assertEquals(123.45, expr.value)
    }

    @Test
    fun `parses unary`() {
        val tokens = listOf(
            Token(TokenValue.Minus, 1, 1),
            Token(TokenValue.Number(123.45), 1, 2),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        assertTrue(expr is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operator)
        assertTrue(expr.operand is Expression.NumberLiteral)
        assertEquals(123.45, expr.operand.value)
    }

    @Test
    fun `parses unary multiple`() {
        // -(-(-123.45))
        val tokens = listOf(
            Token(TokenValue.Minus, 1, 1),
            Token(TokenValue.Minus, 1, 2),
            Token(TokenValue.Minus, 1, 3),
            Token(TokenValue.Number(123.45), 1, 4),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // -(-(-123.45))
        assertTrue(expr is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operator)
        // -(-123.45)
        assertTrue(expr.operand is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operand.operator)
        // -123.45
        assertTrue(expr.operand.operand is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operand.operand.operator)
        // 123.45
        assertTrue(expr.operand.operand.operand is Expression.NumberLiteral)
        assertEquals(123.45, expr.operand.operand.operand.value)
    }

    @Test
    fun `parses factor`() {
        // 123.45 + (67.89 - 3)
        val tokens = listOf(
            Token(TokenValue.Number(123.45), 1, 1),
            Token(TokenValue.Plus, 1, 7),
            Token(TokenValue.Number(67.89), 1, 8),
            Token(TokenValue.Minus, 1, 13),
            Token(TokenValue.Number(3.0), 1, 14),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // 123.45 + (67.89 - 3)
        assertTrue(expr is Expression.Binary)
        assertEquals(TokenValue.Plus, expr.operator)

        assertTrue(expr.left is Expression.NumberLiteral)
        assertEquals(123.45, expr.left.value)

        // 67.89 - 3
        assertTrue(expr.right is Expression.Binary)
        assertEquals(TokenValue.Minus, expr.right.operator)

        assertTrue(expr.right.left is Expression.NumberLiteral)
        assertEquals(67.89, expr.right.left.value)

        assertTrue(expr.right.right is Expression.NumberLiteral)
        assertEquals(3.0, expr.right.right.value)
    }

    @Test
    fun `parses term`() {
        // 123.45 * (25 / 5)
        val tokens = listOf(
            Token(TokenValue.Number(123.45), 1, 1),
            Token(TokenValue.Star, 1, 7),
            Token(TokenValue.Number(25.0), 1, 8),
            Token(TokenValue.Slash, 1, 13),
            Token(TokenValue.Number(5.0), 1, 14),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // 123.45 * (25 / 5)
        assertTrue(expr is Expression.Binary)
        assertEquals(TokenValue.Star, expr.operator)

        assertTrue(expr.left is Expression.NumberLiteral)
        assertEquals(123.45, expr.left.value)

        // 25 / 5
        assertTrue(expr.right is Expression.Binary)
        assertEquals(TokenValue.Slash, expr.right.operator)

        assertTrue(expr.right.left is Expression.NumberLiteral)
        assertEquals(25.0, expr.right.left.value)

        assertTrue(expr.right.right is Expression.NumberLiteral)
        assertEquals(5.0, expr.right.right.value)
    }

    @Test
    fun `parses term with factor`() {
        // 12 * 25 + 5 / 3 => (12 * 25) + (5 / 3)
        val tokens = listOf(
            Token(TokenValue.Number(12.0), 1, 1),
            Token(TokenValue.Star, 1, 3),
            Token(TokenValue.Number(25.0), 1, 5),
            Token(TokenValue.Plus, 1, 6),
            Token(TokenValue.Number(5.0), 1, 8),
            Token(TokenValue.Slash, 1, 9),
            Token(TokenValue.Number(3.0), 1, 11),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // (12 * 25) + (5 / 3)
        assertTrue(expr is Expression.Binary)
        assertEquals(TokenValue.Plus, expr.operator)

        run { // (12 * 25)
            assertTrue(expr.left is Expression.Binary)

            val left_expr = expr.left
            assertEquals(TokenValue.Star, left_expr.operator)

            assertTrue(left_expr.left is Expression.NumberLiteral)
            assertEquals(12.0, left_expr.left.value)

            assertTrue(left_expr.right is Expression.NumberLiteral)
            assertEquals(25.0, left_expr.right.value)
        }

        run { // (5 / 3)
            val right = expr.right

            assertTrue(right is Expression.Binary)
            assertEquals(TokenValue.Slash, right.operator)

            assertTrue(right.left is Expression.NumberLiteral)
            assertEquals(5.0, right.left.value)

            assertTrue(right.right is Expression.NumberLiteral)
            assertEquals(3.0, right.right.value)
        }
    }
}
