/*
 * This source file was generated by the Gradle 'init' task
 */
package lang

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlin.test.assertIs


class TokenizerTest {
    @Test
    fun `tokenizes input successfully`() {
        val input = "+-* / :=;print println"
        val tokens = tokenizerRun(input)

        val expected = listOf(
            Token(TokenValue.Plus, 1, 1),
            Token(TokenValue.Minus, 1, 2),
            Token(TokenValue.Star, 1, 3),
            Token(TokenValue.Slash, 1, 5),
            Token(TokenValue.ColonEqual, 1, 7),
            Token(TokenValue.Semicolon, 1, 9),
            Token(TokenValue.Print(false), 1, 10),
            Token(TokenValue.Print(true), 1, 16)
        )

        assertTrue(tokens.size == expected.size)
        for (i in tokens.indices) {
            assertEquals(expected[i], tokens[i])
        }
    }

    @Test
    fun `tokenizes number`() {
        val input = "123.45"
        val tokens = tokenizerRun(input)

        val expected = listOf(
            Token(TokenValue.Number(123.45), 1, 1)
        )

        assertTrue(tokens.size == expected.size)
        for (i in tokens.indices) {
            assertEquals(expected[i], tokens[i])
        }
    }

    @Test
    fun `parses identifier`() {
        val input = "foo"
        val tokens = tokenizerRun(input)

        assertTrue(tokens.size == 1)
        assertEquals(Token(TokenValue.Ident("foo"), 1, 1), tokens[0])
    }

    @Test
    fun `throws TokenizerError on invalid number`() {
        val input = "123.45.67"
        val expection = assertFailsWith(TokenizerError::class) {
            tokenizerRun(input)
        }
        assertEquals("Tokenizer error at 1:10: Invalid number: 123.45.67", expection.message)
    }

    @Test
    fun `throws TokenizerError on unexpected character`() {
        val input = "@"
        val expection = assertFailsWith(TokenizerError::class) {
            tokenizerRun(input)
        }
        assertEquals("Tokenizer error at 1:1: Unexpected token: @", expection.message)
    }
}

class ParserTest {
    @Test
    fun `parses number`() {
        val tokens = listOf(Token(TokenValue.Number(123.45), 1, 1))
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        assertTrue(expr is Expression.NumberLiteral)
        assertEquals(123.45, expr.value)
    }

    @Test
    fun `parses unary`() {
        val tokens = listOf(
            Token(TokenValue.Minus, 1, 1),
            Token(TokenValue.Number(123.45), 1, 2),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        assertTrue(expr is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operator)
        assertTrue(expr.operand is Expression.NumberLiteral)
        assertEquals(123.45, expr.operand.value)
    }

    @Test
    fun `parses unary multiple`() {
        // -(-(-123.45))
        val tokens = listOf(
            Token(TokenValue.Minus, 1, 1),
            Token(TokenValue.Minus, 1, 2),
            Token(TokenValue.Minus, 1, 3),
            Token(TokenValue.Number(123.45), 1, 4),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // -(-(-123.45))
        assertTrue(expr is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operator)
        // -(-123.45)
        assertTrue(expr.operand is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operand.operator)
        // -123.45
        assertTrue(expr.operand.operand is Expression.Unary)
        assertEquals(TokenValue.Minus, expr.operand.operand.operator)
        // 123.45
        assertTrue(expr.operand.operand.operand is Expression.NumberLiteral)
        assertEquals(123.45, expr.operand.operand.operand.value)
    }

    @Test
    fun `parses factor`() {
        // (123.45 + 67.89) - 3
        val tokens = listOf(
            Token(TokenValue.Number(123.45), 1, 1),
            Token(TokenValue.Plus, 1, 7),
            Token(TokenValue.Number(67.89), 1, 8),
            Token(TokenValue.Minus, 1, 13),
            Token(TokenValue.Number(3.0), 1, 14),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // (123.45 + 67.89) - 3
        assertIs<Expression.Binary>(expr)
        assertIs<TokenValue.Minus>(expr.operator)

        // 123.45 + 67.89
        assertIs<Expression.Binary>(expr.left)
        assertIs<TokenValue.Plus>(expr.left.operator)

        assertIs<Expression.NumberLiteral>(expr.left.left)
        assertEquals(123.45, expr.left.left.value)

        assertIs<Expression.NumberLiteral>(expr.left.right)
        assertEquals(67.89, expr.left.right.value)

        // 3
        assertIs<Expression.NumberLiteral>(expr.right)
        assertEquals(3.0, expr.right.value)
    }

    @Test
    fun `parses term`() {
        // (123.45 * 25) / 5
        val tokens = listOf(
            Token(TokenValue.Number(123.45), 1, 1),
            Token(TokenValue.Star, 1, 7),
            Token(TokenValue.Number(25.0), 1, 8),
            Token(TokenValue.Slash, 1, 13),
            Token(TokenValue.Number(5.0), 1, 14),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // (123.45 * 25) / 5
        assertIs<Expression.Binary>(expr)
        assertEquals(TokenValue.Slash, expr.operator)

        // 123.45 * 25
        assertIs<Expression.Binary>(expr.left)
        assertEquals(TokenValue.Star, expr.left.operator)

        assertIs<Expression.NumberLiteral>(expr.left.left)
        assertEquals(123.45, expr.left.left.value)

        assertIs<Expression.NumberLiteral>(expr.left.right)
        assertEquals(25.0, expr.left.right.value)

        // 5
        assertIs<Expression.NumberLiteral>(expr.right)
        assertEquals(5.0, expr.right.value)
    }

    @Test
    fun `parses term with factor`() {
        // 12 * 25 + 5 / 3 => (12 * 25) + (5 / 3)
        val tokens = listOf(
            Token(TokenValue.Number(12.0), 1, 1),
            Token(TokenValue.Star, 1, 3),
            Token(TokenValue.Number(25.0), 1, 5),
            Token(TokenValue.Plus, 1, 6),
            Token(TokenValue.Number(5.0), 1, 8),
            Token(TokenValue.Slash, 1, 9),
            Token(TokenValue.Number(3.0), 1, 11),
        )
        val parser = Parser(tokens)
        val expr = parser.parseExpression()

        // (12 * 25) + (5 / 3)
        assertTrue(expr is Expression.Binary)
        assertEquals(TokenValue.Plus, expr.operator)

        run { // (12 * 25)
            assertTrue(expr.left is Expression.Binary)

            val left_expr = expr.left
            assertEquals(TokenValue.Star, left_expr.operator)

            assertTrue(left_expr.left is Expression.NumberLiteral)
            assertEquals(12.0, left_expr.left.value)

            assertTrue(left_expr.right is Expression.NumberLiteral)
            assertEquals(25.0, left_expr.right.value)
        }

        run { // (5 / 3)
            val right = expr.right

            assertTrue(right is Expression.Binary)
            assertEquals(TokenValue.Slash, right.operator)

            assertTrue(right.left is Expression.NumberLiteral)
            assertEquals(5.0, right.left.value)

            assertTrue(right.right is Expression.NumberLiteral)
            assertEquals(3.0, right.right.value)
        }
    }

    @Test
    fun `parses variable declaration`() {
        val tokens = listOf(
            Token(TokenValue.Ident("foo"), 1, 1),
            Token(TokenValue.Semicolon, 1, 4),
        )

        val parser = Parser(tokens)
        val stmt = parser.parseStatement()

        assertTrue(stmt is Statement.VariableDeclaration)
        assertEquals("foo", stmt.name)
        assertTrue(stmt.value == null)
    }

    @Test
    fun `parses variable declaration with expression`() {
        val tokens = listOf(
            Token(TokenValue.Ident("foo"), 1, 1),
            Token(TokenValue.ColonEqual, 1, 4),
            Token(TokenValue.Number(12.0), 1, 6),
            Token(TokenValue.Semicolon, 1, 7),
        )

        val parser = Parser(tokens)
        val stmt = parser.parseStatement()

        assertTrue(stmt is Statement.VariableDeclaration)
        assertEquals("foo", stmt.name)
        assertTrue(stmt.value is Expression.NumberLiteral)
        assertEquals(12.0, stmt.value.value)
    }

    @Test
    fun `parses indentifier in expression`() {
        val tokens = listOf(
            Token(TokenValue.Ident("foo"), 1, 1),
            Token(TokenValue.ColonEqual, 1, 4),
            Token(TokenValue.Ident("bar"), 1, 5),
            Token(TokenValue.Semicolon, 1, 8),
        )

        val parser = Parser(tokens)
        val stmt = parser.parseStatement()

        assertTrue(stmt is Statement.VariableDeclaration)
        assertEquals("foo", stmt.name)
        assertTrue(stmt.value is Expression.Ident)
        assertEquals("bar", stmt.value.name)
    }

    @Test
    fun `parses multiple statements`() {
        val tokens = listOf(
            Token(TokenValue.Ident("foo"), 1, 1),
            Token(TokenValue.Semicolon, 1, 4),
            Token(TokenValue.Ident("bar"), 2, 1),
            Token(TokenValue.Semicolon, 2, 4),
        )

        val parser = Parser(tokens)
        val statements = parser.parseProgram()
        assertEquals(2, statements.size)

        run {
            val foo = statements[0]
            assertTrue(foo is Statement.VariableDeclaration)
            assertEquals("foo", foo.name)
        }

        run {
            val bar = statements[1]
            assertTrue(bar is Statement.VariableDeclaration)
            assertEquals("bar", bar.name)
        }
    }

    @Test
    fun `parses print statement`() {
        val tokens = listOf(
            Token(TokenValue.Print(false), 1, 1),
            Token(TokenValue.Number(123.45), 1, 6),
            Token(TokenValue.Semicolon, 1, 11),
        )

        val parser = Parser(tokens)
        val stmt = parser.parseStatement()

        assertTrue(stmt is Statement.Print)
        assertTrue(stmt.expression is Expression.NumberLiteral)
        assertEquals(123.45, stmt.expression.value)
        assertFalse(stmt.ln)
    }
}

class InterpreterTest {
    @Test
    fun `interprets variable declaration`() {
        val interpreter = Interpreter()
        val stmt = Statement.VariableDeclaration("foo", Expression.NumberLiteral(12.0))
        interpreter.interpretProgram(listOf(stmt))

        assertEquals(VariableValue.Double(12.0), interpreter.variables["foo"])
    }

    @Test
    fun `interprets print statement`() {
        val printer = BufferedPrinter()

        val interpreter = Interpreter(printer)
        val stmt = listOf(
            Statement.Print(Expression.NumberLiteral(123.45), false),
            Statement.Print(Expression.NumberLiteral(22.0), true)
        )
        interpreter.interpretProgram(stmt)

        assertEquals("123.4522.0\n", printer.sb.toString())
    }
}
