/*
 * This source file was generated by the Gradle 'init' task
 */
package lang

import kotlin.test.*

fun ident(name: String, line: Int = 0, col: Int = 0): Expression =
    Expression(ExpressionType.Ident(name), line, col)

fun num(value: Double, line: Int = 0, col: Int = 0): Expression =
    Expression(ExpressionType.NumberLiteral(value), line, col)

fun str(value: String, line: Int = 0, col: Int = 0): Expression =
    Expression(ExpressionType.StringLiteral(value), line, col)

fun bool(value: Boolean, line: Int = 0, col: Int = 0): Expression =
    Expression(ExpressionType.BoolLiteral(value), line, col)

fun unary(operator: TokenValue, operand: Expression, line: Int = 0, col: Int = 0): Expression =
    Expression(ExpressionType.Unary(operator, operand), line, col)

fun binary(operator: TokenValue, left: Expression, right: Expression, line: Int = 0, col: Int = 0): Expression =
    Expression(ExpressionType.Binary(operator, left, right), line, col)

fun varDecl(name: String, type: VariableType?, value: Expression?, line: Int = 0, col: Int = 0): Statement =
    Statement(StatementType.VariableDeclaration(name, type, value), line, col)

fun printStmt(value: Expression, ln: Boolean, line: Int = 0, col: Int = 0): Statement =
    Statement(StatementType.Print(value, ln), line, col)

fun varAssignment(name: String, value: Expression, line: Int = 0, col: Int = 0): Statement =
    Statement(StatementType.VariableAssignment(name, value), line, col)

fun block(stmts: List<Statement>, line: Int = 0, col: Int = 0): Statement =
    Statement(StatementType.Block(stmts), line, col)

fun forStmt(
    condition: Expression?,
    body: Statement,
    line: Int = 0,
    col: Int = 0
): Statement =
    Statement(StatementType.For(condition, body), line, col)

fun cForStmt(
    init: Statement?,
    condition: Expression?,
    update: Statement?,
    body: Statement,
    line: Int = 0,
    col: Int = 0
): Statement =
    Statement(StatementType.CFor(init, condition, update, body), line, col)

fun ifStmt(
    condition: Expression,
    thenBranch: Statement,
    elseBranch: Statement? = null,
    line: Int = 0,
    col: Int = 0
): Statement =
    Statement(StatementType.If(condition, thenBranch, elseBranch), line, col)

fun funParam(
    name: String,
    type: VariableType,
    line: Int = 0,
    col: Int = 0
): FunctionParameter =
    FunctionParameter(name, type, line, col)

fun funDecl(
    name: String,
    params: List<FunctionParameter>,
    ret: VariableType?,
    body: Statement,
    line: Int = 0,
    col: Int = 0
): Statement =
    Statement(StatementType.FunctionDeclaration(name, params, ret, body), line, col)

fun returnStmt(
    value: Expression,
    line: Int = 0,
    col: Int = 0
): Statement =
    Statement(StatementType.Return(value), line, col)

fun call(name: String, args: List<Expression>, line: Int = 0, col: Int = 0): Expression =
    Expression(ExpressionType.Call(name, args), line, col)

fun callStmt(name: String, args: List<Expression>, line: Int = 0, col: Int = 0): Statement =
    Statement(StatementType.Call(name, args), line, col)

class InterpreterTest {
    @Test
    fun `interprets unary`() {
        data class Input(
            val name: String,
            val expr: Expression,
            val expected: VariableValue,
        )

        val inputs = listOf(
            // !true
            Input(
                "!true",
                unary(TokenValue.Excl, bool(true)),
                VariableValue.Bool(false)
            ),
            // -12.0
            Input(
                "-12.0",
                unary(TokenValue.Minus, num(12.0)),
                VariableValue.Number(-12.0)
            ),
            // --12.0
            Input(
                "--12.0",
                unary(TokenValue.Minus, unary(TokenValue.Minus, num(12.0))),
                VariableValue.Number(12.0)
            ),
        )

        for (input in inputs) {
            var result = Interpreter().interpretExpression(input.expr)
            assertEquals(input.expected, result, "Failed to interpret unary: ${input.expr}")
        }
    }

    @Test
    fun `interprets binary`() {
        data class Input(
            val name: String,
            val expr: Expression,
            val expected: VariableValue,
        )

        val inputs = listOf(
            // true || false && true => true
            Input(
                "true || false && true => true",
                binary(
                    TokenValue.DoubleAmp,
                    binary(
                        TokenValue.DoublePipe,
                        bool(true),
                        bool(false),
                    ),
                    bool(true),
                ),
                VariableValue.Bool(true),
            ),
            // 123 + 123 => 246
            Input(
                "123 + 123 => 246",
                binary(TokenValue.Plus, num(123.0), num(123.0)),
                VariableValue.Number(246.0),
            ),
        )

        for (input in inputs) {
            val result = Interpreter().interpretExpression(input.expr)
            assertEquals(input.expected, result, "Failed to interpret binary ${input.name}")
        }
    }

    @Test
    fun `parses statement`() {
        data class Input(
            val name: String,
            val stmt: List<Statement>,
            val expected: (interpreter: Interpreter) -> Unit,
        )

        val inputs = listOf(
            Input(
                "foo := 12.0;",
                listOf(varDecl("foo", null, num(12.0))),
                { interpreter ->
                    assertEquals(VariableValue.Number(12.0), interpreter.varEnv.get("foo"))
                },
            ),
            Input(
                "println 12.0; print \"123\"",
                listOf(
                    printStmt(num(12.0), true),
                    printStmt(str("123"), false),
                ),
                { interpreter ->
                    val printer = interpreter.printer
                    assertNotNull(printer)
                    val buffered = printer.sb.toString()
                    val expected = "12.0\n123"
                    assertEquals(expected, buffered)
                },
            ),
            Input(
                "x := 5; x = 10;",
                listOf(
                    varDecl("x", null, num(5.0)),
                    varAssignment("x", num(10.0)),
                ),
                { interpreter ->
                    assertEquals(VariableValue.Number(10.0), interpreter.varEnv.get("x"))
                },
            ),
            Input(
                "x := 5; { x = 10 }",
                listOf(
                    varDecl("x", null, num(5.0)),
                    block(listOf(varAssignment("x", num(10.0)))),
                ),
                { interpreter ->
                    assertEquals(VariableValue.Number(10.0), interpreter.varEnv.get("x"))
                },
            ),
            Input(
                "{ x := 5; }",
                listOf(block(listOf(varDecl("x", null, num(5.0))))),
                { interpreter ->
                    assertNull(interpreter.varEnv.get("x"))
                },
            ),
            Input(
                "x := 10; if true { x = 5 } else { x = 15 }",
                listOf(
                    varDecl("x", null, num(10.0)),
                    ifStmt(
                        bool(true),
                        block(listOf(varAssignment("x", num(5.0)))),
                        block(listOf(varAssignment("x", num(15.0))))
                    )
                ),
                { interpreter ->
                    assertEquals(VariableValue.Number(5.0), interpreter.varEnv.get("x"))
                },
            ),
            Input(
                "x := 10; if false { } else if false { x = 5 } else { x = 20 }",
                listOf(
                    varDecl("x", null, num(10.0)),
                    ifStmt(
                        bool(false),
                        block(listOf()),
                        ifStmt(
                            bool(false),
                            block(listOf()),
                            block(listOf(varAssignment("x", num(20.0))))
                        )
                    )
                ),
                { interpreter ->
                    assertEquals(VariableValue.Number(20.0), interpreter.varEnv.get("x"))
                },
            ),

            Input(
                "fn foo(x: number) {  }",
                listOf(
                    funDecl(
                        "foo",
                        listOf(funParam("x", VariableType.Number)),
                        null,
                        block(listOf()),
                    )
                ),
                { interpreter ->
                    val func = interpreter.funcEnv.get("foo")
                    assertNotNull(func)
                    assertEquals(1, func.params.size)
                    val param = func.params[0]
                    assertEquals("x", param.name)
                    assertEquals(VariableType.Number, param.type)
                    assertEquals(0, func.body.statements.size)
                },
            )
        )

        for (input in inputs) {
            println("Testing ${input.name}")
            try {
                val printer = BufferedPrinter()
                val interpreter = Interpreter(printer)
                interpreter.interpretProgram(input.stmt)
                input.expected(interpreter)
            } catch (e: LangError) {
                fail("Failed to parse ${input.name}: ${e.message}")
            }
        }
    }

    @Test
    fun `interprets function call`() {
        // fun foo(): number {
        //  return 5;
        // }
        // x := foo();

        val program = listOf(
            funDecl(
                "foo",
                listOf(),
                VariableType.Number,
                block(listOf(returnStmt(num(5.0)))),
            ),
            varDecl("x", null, call("foo", listOf())),
        )

        val interpreter = Interpreter()
        interpreter.interpretProgram(program)

        val foo = interpreter.funcEnv.get("foo")
        assertNotNull(foo)

        val x = interpreter.varEnv.get("x")
        assertEquals(VariableValue.Number(5.0), x)
    }
}
