/*
 * This source file was generated by the Gradle 'init' task
 */
package lang

import kotlin.test.*

class InterpreterTest {
    @Test
    fun `interprets unary bool negation`() {
        val expr = Expression.Unary(
            operator = TokenValue.Excl,
            operand = Expression.BoolLiteral(true),
        )
        val interpreter = Interpreter()
        val result = interpreter.interpretUnary(expr)

        assertEquals(VariableValue.Bool(false), result)
    }

    @Test
    fun `interprets unary number negation`() {
        val expr = Expression.Unary(
            operator = TokenValue.Minus,
            operand = Expression.NumberLiteral(12.0),
        )
        val interpreter = Interpreter()
        val result = interpreter.interpretUnary(expr)

        assertEquals(VariableValue.Number(-12.0), result)
    }

    @Test
    fun `interprets unary number negation nested`() {
        val expr = Expression.Unary(
            operator = TokenValue.Minus,
            operand = Expression.Unary(
                operator = TokenValue.Minus,
                operand = Expression.NumberLiteral(12.0),
            ),
        )
        val interpreter = Interpreter()
        val result = interpreter.interpretUnary(expr)

        assertEquals(VariableValue.Number(12.0), result)
    }

    @Test
    fun `interprets variable declaration`() {
        val interpreter = Interpreter()
        val stmt = Statement.VariableDeclaration("foo", null, Expression.NumberLiteral(12.0))
        interpreter.interpretProgram(listOf(stmt))

        assertEquals(VariableValue.Number(12.0), interpreter.scopes[0]["foo"])
    }

    @Test
    fun `interprets print statement`() {
        val printer = BufferedPrinter()

        val interpreter = Interpreter(printer)
        val stmt = listOf(
            Statement.Print(Expression.NumberLiteral(123.45), false),
            Statement.Print(Expression.NumberLiteral(22.0), true)
        )
        interpreter.interpretProgram(stmt)

        assertEquals("123.4522.0\n", printer.sb.toString())
    }

    @Test
    fun `interprets variable assignment`() {
        val interpreter = Interpreter()
        val stmt = listOf(
            Statement.VariableDeclaration("foo", null, Expression.NumberLiteral(12.0)),
            Statement.VariableAssignment("foo", Expression.NumberLiteral(22.0))
        )
        interpreter.interpretProgram(stmt)

        assertEquals(VariableValue.Number(22.0), interpreter.scopes[0]["foo"])
    }

    @Test
    fun `interprets block`() {
        val interpreter = Interpreter()
        val stmt = listOf(
            Statement.VariableDeclaration("foo", null, Expression.NumberLiteral(12.0)),
            Statement.Block(
                listOf(
                    Statement.VariableAssignment("foo", Expression.NumberLiteral(22.0))
                )
            )
        )
        interpreter.interpretProgram(stmt)

        assertEquals(VariableValue.Number(22.0), interpreter.scopes[0]["foo"])
    }

    @Test
    fun `disposes scope`() {
        val interpreter = Interpreter()
        val stmt = listOf(
            Statement.Block(
                listOf(
                    Statement.VariableDeclaration("foo", null, Expression.NumberLiteral(12.0))
                )
            )
        )
        interpreter.interpretProgram(stmt)
        assertEquals(1, interpreter.scopes.size)

        val globalScope = interpreter.scopes[0]
        assertEquals(0, globalScope.size)
    }
}
